[package]
name = "module_16_concurrency_parallelism"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "basic"
path = "src/basic.rs"

[[bin]]
name = "passing_data"
path = "src/passing_data.rs"

[[bin]]
name = "passing_data2"
path = "src/passing_data2.rs"

[[bin]]
name = "mutex"
path = "src/mutex.rs"

[dependencies]
rand = "0.10.1"
